import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { LogOut, Trash2, Star, Upload, MessageSquare, Images, ClipboardList } from 'lucide-react';
import api from '../api';

export default function AdminDashboard(){const nav=useNavigate();const[token]=useState(localStorage.getItem('adminToken'));const[tab,setTab]=useState('quotes');const[quotes,setQuotes]=useState([]);const[reviews,setReviews]=useState([]);const[projects,setProjects]=useState([]);const[review,setReview]=useState({customerName:'',location:'',rating:5,service:'',comment:''});const[project,setProject]=useState({title:'',service:'',location:'',description:'',beforeImage:null,afterImage:null});const[msg,setMsg]=useState('');
 useEffect(()=>{if(!token){nav('/admin/login');return}refresh()},[token]);
 async function refresh(){try{const [q,r,b]=await Promise.all([api.get('/quotes'),api.get('/testimonials'),api.get('/before-after')]);setQuotes(q.data);setReviews(r.data);setProjects(b.data)}catch(e){if(e.response?.status===401){localStorage.removeItem('adminToken');nav('/admin/login')}}}
 const logout=()=>{localStorage.removeItem('adminToken');nav('/admin/login')};
 async function addReview(e){e.preventDefault();await api.post('/testimonials',review);setReview({customerName:'',location:'',rating:5,service:'',comment:''});setMsg('Review added');refresh()}
 async function addProject(e){e.preventDefault();const fd=new FormData();Object.entries(project).forEach(([k,v])=>{if(v!==null)fd.append(k,v)});await api.post('/before-after',fd,{headers:{'Content-Type':'multipart/form-data'}});setProject({title:'',service:'',location:'',description:'',beforeImage:null,afterImage:null});setMsg('Before/after project added');refresh()}
 async function del(url){if(!confirm('Delete this item?'))return;await api.delete(url);refresh()}
 async function status(id,status){await api.patch(`/quotes/${id}/status`,{status});refresh()}
 return <div className="admin-shell"><aside className="admin-side"><div className="logo light"><span>CP</span><b>CleanPro</b></div><button className={tab==='quotes'?'active':''} onClick={()=>setTab('quotes')}><ClipboardList/> Quote Requests</button><button className={tab==='reviews'?'active':''} onClick={()=>setTab('reviews')}><Star/> Customer Reviews</button><button className={tab==='projects'?'active':''} onClick={()=>setTab('projects')}><Images/> Before & After</button><div className="admin-side-bottom"><a href="/">View Website</a><button onClick={logout}><LogOut/> Logout</button></div></aside><section className="admin-main"><div className="admin-top"><div><span>ADMIN PANEL</span><h1>{tab==='quotes'?'Quote requests':tab==='reviews'?'Customer reviews':'Before & after'}</h1></div><div className="admin-stat"><MessageSquare/> {quotes.filter(q=>q.status==='new').length} new quotes</div></div>{msg&&<div className="success banner">{msg}</div>}
 {tab==='quotes'&&<div className="admin-table-wrap"><table><thead><tr><th>Customer</th><th>Property</th><th>Requested</th><th>Services</th><th>Status</th><th></th></tr></thead><tbody>{quotes.map(q=><tr key={q._id}><td><strong>{q.name}</strong><small>{q.email}<br/>{q.phone}</small></td><td>{q.propertyType||'-'}<small>{q.suburb||q.address||''}</small></td><td>{q.preferredDate||'-'}<small>{new Date(q.createdAt).toLocaleString()}</small></td><td>{[q.pestControl==='Yes'&&'Pest control',q.carpetCleaning==='Yes'&&'Carpet cleaning'].filter(Boolean).join(', ')||'General clean'}</td><td><select value={q.status} onChange={e=>status(q._id,e.target.value)}><option>new</option><option>contacted</option><option>booked</option><option>completed</option></select></td><td><button className="icon-btn danger" onClick={()=>del(`/quotes/${q._id}`)}><Trash2/></button></td></tr>)}</tbody></table>{quotes.length===0&&<div className="empty-admin">No quote requests yet.</div>}</div>}
 {tab==='reviews'&&<div className="admin-content-grid"><form className="admin-card" onSubmit={addReview}><h2>Add customer review</h2><label>Customer name<input required value={review.customerName} onChange={e=>setReview({...review,customerName:e.target.value})}/></label><label>Location<input value={review.location} onChange={e=>setReview({...review,location:e.target.value})}/></label><label>Service<input value={review.service} onChange={e=>setReview({...review,service:e.target.value})}/></label><label>Star rating<select value={review.rating} onChange={e=>setReview({...review,rating:Number(e.target.value)})}>{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><label>Comment<textarea required rows="5" value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})}/></label><button className="btn">Add Review</button></form><div className="admin-list">{reviews.map(r=><div className="admin-review" key={r._id}><div><strong>{r.customerName}</strong><span>{r.service||'Cleaning'} {r.location&&`• ${r.location}`}</span></div><span className="stars">{'★'.repeat(r.rating)}</span><p>{r.comment}</p><button className="icon-btn danger" onClick={()=>del(`/testimonials/${r._id}`)}><Trash2/></button></div>)}{reviews.length===0&&<div className="empty-admin">No reviews added yet.</div>}</div></div>}
 {tab==='projects'&&<div className="admin-content-grid"><form className="admin-card" onSubmit={addProject}><h2>Add before/after project</h2><label>Project title<input required value={project.title} onChange={e=>setProject({...project,title:e.target.value})}/></label><label>Service<input value={project.service} onChange={e=>setProject({...project,service:e.target.value})}/></label><label>Location<input value={project.location} onChange={e=>setProject({...project,location:e.target.value})}/></label><label>Description<textarea rows="3" value={project.description} onChange={e=>setProject({...project,description:e.target.value})}/></label><label>Before image<input required type="file" accept="image/*" onChange={e=>setProject({...project,beforeImage:e.target.files[0]})}/></label><label>After image<input required type="file" accept="image/*" onChange={e=>setProject({...project,afterImage:e.target.files[0]})}/></label><button className="btn"><Upload/> Upload Project</button></form><div className="admin-projects">{projects.map(p=><div className="admin-project" key={p._id}><div><img src={`${api.defaults.baseURL.replace(/\/api$/,'')}${p.beforeImage}`} alt="before"/><img src={`${api.defaults.baseURL.replace(/\/api$/,'')}${p.afterImage}`} alt="after"/></div><strong>{p.title}</strong><span>{p.service} {p.location&&`• ${p.location}`}</span><button className="icon-btn danger" onClick={()=>del(`/before-after/${p._id}`)}><Trash2/></button></div>)}{projects.length===0&&<div className="empty-admin">No projects added yet.</div>}</div></div>}
 </section></div>}
